logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.wulala: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  contextPath:   /auth