server.port: 8903
spring.application.name: bg-console
logging.level.com.wulala.bgconsole.BgConsoleApplicationTests: debug
logging.level.com.wulala.bgconsole.BgConsoleApplication: debug
# 数据库访问配置
# 主数据源，默认的
spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/test
#spring.datasource.username=root
#spring.datasource.password=123456
spring.datasource.url: jdbc:mysql://cdb-8vlvqayx.gz.tencentcdb.com:10094/bgconsole?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username: root
spring.datasource.password: W0wisshit!

mybatis.type-aliases-package: com.wulala.bgconsole.domain.model
#Mapper.xml所在的位置
mybatis.mapper-locations: classpath:/mybatis/mapper/*.xml
mybatis.config-location: classpath:/mybatis/mybatis-config.xml
#pagehelper分页插件配置
pagehelper.helperDialect: mysql
pagehelper.reasonable: true
pagehelper.supportMethodsArguments: true
pagehelper.params.count: countSql